### ISSUE TITLE
How to get AppKey and Developer ID?

### ISSUE THREAD

**Issue by Aaroneisele55** [Playfinity/playfinity-recorder-android#4]
@pfstian In the Manifest, i can set an AppKey and a developer id.
Where do i get those values? ´Where can i register a "dev account" to get them??
Thanks

**Comment by pfstian** [comment]
Hi,

To obtain a developer- and app identifier, we have no automated process. 
You will get it by contacting Playfinity after you have tested out the API and decided that you want to create an app to publish to the store.

While you are developing or testing out the API, you can just use the default/pre-filled test values.

- S

**Comment by Aaroneisele55** [comment]
Thanks @pfstian, i have now understood that i don't need the values for testing
